### ISSUE TITLE
Resolve `evaluation nested too deeply` issues

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/cytominer_scripts#33]
@bethac07 reported this

```
ubuntu@ip-10-0-3-243:~/efs/2019_06_04_Cardiomyocytes_AnantChopra_Bayer/workspace/software/cytominer_scripts$ ./preselect.R \
>   --batch_id ${BATCH_ID} \
>   --input ../../parameters/${BATCH_ID}/sample/${BATCH_ID}_normalized_sample.feather \
>   --operations correlation_threshold
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Execution halted
```

This was reported for `preselect` but it can occur in other functions that use `feather`

The issue appears to be related to this issue https://github.com/wesm/feather/issues/372

Update the packages mentioned here and the problem should go away: https://github.com/wesm/feather/issues/372#issuecomment-485243088

**Comment by bethac07** [comment]
Updating the packages worked.
